services:
  web:
    image: nginx:1.23.1
    ports:
      - "8000:80"
    volumes:
      - ./precisa-se-backend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - cr_net_dev

  app:
    build:
      context: ./php
    volumes:
      - ./precisa-se-backend:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - cr_net_dev
    command: symfony server:start --no-tls
    #depends_on:
    # - postgres
  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/.env.postgres
    volumes:
      - /c/docker/volumes/symfony/postgres/data:/var/lib/postgresql/data:rw
    networks:
      - cr_net_dev

  symfony:
    build:
      context: ./symfony
    volumes:
      - ./precisa-se-backend:/var/www/html
    networks:
      - cr_net_dev
    ports:
      - "8000:9000"
  composer:
    build:
      context: ./composer
    volumes:
      - ./precisa-se-backend:/var/www/html
networks:
  cr_net_dev:
    external: true
